### ISSUE TITLE
Adapting clocking hardware circuit for PCIe endpoint

### ISSUE THREAD

**Issue by ste7anste7an** [rick-heig/eNVMe#2]
I use this issue to discuss a problem that arose after changing the clock hardware of my NanoPC-T6-TLS.

Because the nvme m2 is configured as a root complex, delivering a 100Mhz clock to the nvme drive, problem arise when configuring this interface as a PCIe endpoint and connecting this interface to a host PCIe RC. In that case both interfaces deliver a clock. Especially on hosts using spread spectrum on their PCIe clock, makes things worse.
I decided to changed the clocking circuit according to the pdf file shown below.
[clock_patch.pdf](https://github.com/user-attachments/files/17952854/clock_patch.pdf)

After these changes, the external clock from the host PCIe RC interface is directly (decoupled by 10pF capacitors) delivered to the RockWell chip's PCIe interface. Unfortunately, the second clock to PCIE30_PORT1 is also disabled by removing the U3845. When booting the board with the Ubuntu SD card, the boot process gets stuck when initializing the pcie30 hardware interface with a pcie30 AER error, probably because the clock is missing.

I thought solving this by removing or disabling the 2nd pcie30 interface in the device tree. Unfortunately, I not really understand how that device tree works for the NanoPC-T6-LTS board (which is slightly different from the T6). Therefore, I seek assistance to make changes in the device tree such that upon booting, the RC PCIE30 interface is diabled and the PCIe30 endpoint is enabled.

Could you explain how the device tree depends on the different files (dts and dtso) and how I could disable the PCIe30 RC interface?

**Comment by rick-heig** [comment]
Hello,

You can modify the the files in the linux directory of step 1 in https://github.com/rick-heig/eNVMe/blob/main/doc/platform.md
The device tree files are in [linux/arch/arm64/boot/dts/rockchip](https://github.com/rick-heig/linux/tree/rk3588_ep_v17/arch/arm64/boot/dts/rockchip)

I'd recommend just modifying the overlay https://github.com/rick-heig/linux/blob/rk3588_ep_v17/arch/arm64/boot/dts/rockchip/rk3588-nanopc-t6-pcie-ep.dtso

The overlay adds upon this device tree : https://github.com/rick-heig/linux/blob/rk3588_ep_v17/arch/arm64/boot/dts/rockchip/rk3588-nanopc-t6.dts

Which includes `rk3588-nanopc-t6.dtsi` which itself includes `rk3588.dtsi` etc. you can follow the includes and have a look.

You can disable the 2nd PCIe interface in the overlay with :
```
&pcie2x1l1 {
	status = "disabled";
};
```

I am not 100% sure that this is the one that is waiting for the clock, `pcie3x2` should be disabled by default, so maybe it could also be `pcie2x1l0`. Anyways you can disable them in the overlay with the same logic as shown above.

You might also change : 
```
&pcie30phy {
	rockchip,rx-common-refclk-mode = <0 0 0 0>;
};
```

to

```
&pcie30phy {
	rockchip,rx-common-refclk-mode = <1 1 1 1>;
};
```

Because now you want to operate in common reference clock mode between RC and EP in PCIe. [RK3588 technical reference manual](https://github.com/FanX-Tek/rk3588-TRM-and-Datasheet) states :
"rxX_cmn_refclk_mode
RX common reference clock mode for lane X.
This mode should be enabled only when the far-end and near-end devices are running with a common reference clock. When asserted, this input configures the elastic buffer to operate in the lowest latency mode."

Once you changed the overlay or device trees, you can recompile them by going in the `buildroot` directory of step 1 and run `make linux-rebuild all`, this should be quite fast and you will see in the logs that the device tree files are being recompiled.

You can then copy the compiled device tree files to the SD, the newly compiled device tree files will be in `buildroot/output/build/linux-custom/arch/arm64/boot/dts/rockchip/`.

If you want to be sure about the contents of the compiled device tree files you can decompile them with `dtc` (the device tree compiler) and check.

`dtc -I dtb -O dts buildroot/output/build/linux-custom/arch/arm64/boot/dts/rockchip/rk3588-nanopc-t6-pcie-ep.dtbo | less`

Best of luck.
Rick

**Comment by ste7anste7an** [comment]
Thank you for your extensive answer. This will be very helpfull to try disabling the PCIe RC. I will try it next week. Keep you updated on this issue.

**Comment by ste7anste7an** [comment]
I close this issue. It did not work out as expected by rearraging the clocks. Using a pcie sqitch between the host and the NanoPC T6 solved the clocking issues completely. So I use an unaltered board now and that seems to work fine.
